live.chess.client.versionInfo.lccVersion = 4.0.28
live.chess.client.versionInfo.cometDVersion = 5.0.22
live.chess.client.versionInfo.jettyVersion = 9.4.58.v20250814
live.chess.client.versionInfo.protocolVersion = 2.1
